# Generated by Django 4.2.7 on 2025-12-06 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('WL', 'Pérdida de peso'), ('MG', 'Ganancia muscular'), ('MT', 'Mantenimiento'), ('EN', 'Resistencia')], max_length=2)),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentario (poco o ningún ejercicio)'), (1.375, 'Ligero (ejercicio 1-3 días/semana)'), (1.55, 'Moderado (ejercicio 3-5 días/semana)'), (1.725, 'Activo (ejercicio 6-7 días/semana)'), (1.9, 'Muy activo (ejercicio intenso diario)')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.FloatField(help_text='Peso en kg', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('height', models.FloatField(help_text='Altura en cm', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('bmr', models.FloatField(blank=True, help_text='Tasa metabólica basal', null=True)),
                ('tdee', models.FloatField(blank=True, help_text='Gasto energético total diario', null=True)),
                ('target_calories', models.FloatField(blank=True, null=True)),
                ('protein_ratio', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.6)])),
                ('carbs_ratio', models.FloatField(default=0.4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.7)])),
                ('fat_ratio', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.5)])),
                ('daily_meals', models.JSONField(default=dict, help_text='Estructura de comidas diarias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('BR', 'Desayuno'), ('LU', 'Almuerzo'), ('DI', 'Cena'), ('SN', 'Merienda'), ('PW', 'Pre-entreno'), ('PO', 'Post-entreno')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0, help_text='Gramos de proteína')),
                ('carbs', models.IntegerField(default=0, help_text='Gramos de carbohidratos')),
                ('fat', models.IntegerField(default=0, help_text='Gramos de grasa')),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.mealplan')),
                ('suggested_products', models.ManyToManyField(blank=True, to='store.product')),
            ],
            options={
                'ordering': ['time_of_day'],
            },
        ),
    ]
