# Generated by Django 4.2.7 on 2025-12-08 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='daily_meals',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Light (exercise 1-3 days/week)'), (1.55, 'Moderate (exercise 3-5 days/week)'), (1.725, 'Active (exercise 6-7 days/week)'), (1.9, 'Very active (hard exercise daily)')]),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='bmr',
            field=models.FloatField(blank=True, help_text='Basal Metabolic Rate', null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(choices=[('WL', 'Weight Loss'), ('MG', 'Muscle Gain'), ('MT', 'Maintenance'), ('EN', 'Endurance')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='height',
            field=models.FloatField(help_text='Height in cm', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='tdee',
            field=models.FloatField(blank=True, help_text='Total Daily Energy Expenditure', null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='weight',
            field=models.FloatField(help_text='Weight in kg', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
